/**:
  ros__parameters:
    # ----- Image sensor -----
    image_width: 960
    image_height: 540

    # 4mm
    # ----- Intrinsic matrix (pinhole) -----
    fx: 629.8477
    fy: 629.7639
    cx: 492.1117
    cy: 277.6097

    # ----- Radtan distortion [k1, k2, p1, p2] -----
    dist_coeffs: [0.0, 0.0 ,0.0 ,0.0] # [0.03458671, -0.15489642, -0.00036472, 0.00026632]

    # ----- Noise -----
    noise_sigma: 1.5  # Gaussian pixel noise std-dev (pixels)

    # ----- Imperfections -----
    max_range: 100.0                # Max detection range in meters
    false_detection_prob: 0.05       # Probability (0-1) of generating a false detection instead of true target
    dropout_prob_at_max_range: 0.0  # Dropout probability at max range. Increases linearly from 0 at range 0.
    delay_ms: 1                     # Simulated camera detection delay in milliseconds
    log_dir: "/home/ituarc/Documents/Github/Delayed-KalmanFilter-VisualGuidance/eskf_py/interceptor_sensor_emulators/log/camera"

    # ----- Rate -----
    rate_hz: 30.0

    # ----- Visualization -----
    visualize_target: false

    # ----- Topics (override via launch or CLI) -----
    interceptor_lla_topic: /mavros/global_position/global
    target_lla_topic: /target/telemetry/state
    interceptor_local_odom_topic: /mavros/global_position/local
    state_topic: /mavros/state
    target_pixel_topic: /interceptor/camera/target_pbar_
    target_pixel_true_topic: /interceptor/camera/target_pbar_true
