topics:
  imu: "/mavros/imu/data_raw"    #for angular veloicty
  image: "/interceptor/camera/target_pbar"
  radar: "/radar/emulated_measurement"
  interceptor_odom: "/mavros/global_position/local"   # for interceptor pos,vel,Rb2e
  interceptor_state: "/mavros/state" # mavros state topic
  output_state: "/eskf_reduced/odom"
  output_pose: "/eskf_reduced/pbar"
  output_roi: "/interceptor/camera/inference_roi"
  output_relative_position: "/eskf_reduced/pr"

timing:
  imu_rate_hz: 200
  eskf_rate_hz: 200
  image_delay_ms: 150
  image_timeout_sec: 1.0

delay_compensation:
  enable_extrapolation: true

measurement_noise:
  image_sigma: 0.03
  radar_sigma_pos: 10.0
  radar_sigma_vel: 0.5
  radar_noise_inflation: 2.0

radar:
  use_vr: false  #velocity measurement
  measurement_is_relative: false

reduced_filter:
  target_rw_sigma: 1.5

initial_covariance:
  position: 5.0
  velocity: 1.0
  pbar: 0.05

camera:
  R_b2c: [0, 1, 0,
          0, 0, 1,
          1, 0, 0]
  min_depth: 1
  roi_distance_threshold: 40.0
  fx: 1238.10428
  fy: 1238.78782
  cx: 960.0
  cy: 540.0

history:
  buffer_length: 40

chi2_gating:
  enable_false_detection_image: true
  enable_false_detection_radar: true
  image_threshold: 18.43
  radar_threshold_3dof: 100.37
  radar_threshold_6dof: 27.86

logging:
  enable: true
  rate_hz: 50.0
  log_dir: "/home/ituarc/ros2_ws/src/eskf_cpp_reduced/log"
  radar_csv_dir: "/home/ituarc/Documents/Github/Delayed-KalmanFilter-VisualGuidance/eskf_py/interceptor_sensor_emulators/log/radar"
  camera_csv_dir: "/home/ituarc/Documents/Github/Delayed-KalmanFilter-VisualGuidance/eskf_py/interceptor_sensor_emulators/log/camera"
